export const schema = {
  models: {
    Analytics: {
      name: "Analytics",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        traffic: {
          name: "traffic",
          isArray: true,
          type: {
            nonModel: "Traffic",
          },
          isRequired: true,
          attributes: [],
          isArrayNullable: false,
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: "Analytics",
      attributes: [
        {
          type: "model",
          properties: {},
        },
      ],
    },
    Companies: {
      name: "Companies",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        legalName: {
          name: "legalName",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        tradingName: {
          name: "tradingName",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        email: {
          name: "email",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        password: {
          name: "password",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        lastPasswordGen: {
          name: "lastPasswordGen",
          isArray: false,
          type: "AWSDateTime",
          isRequired: true,
          attributes: [],
        },
        billingAddress: {
          name: "billingAddress",
          isArray: false,
          type: {
            nonModel: "BillingAddress",
          },
          isRequired: false,
          attributes: [],
        },
        planHistory: {
          name: "planHistory",
          isArray: true,
          type: {
            nonModel: "PlanHistory",
          },
          isRequired: true,
          attributes: [],
          isArrayNullable: true,
        },
        stripeId: {
          name: "stripeId",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        registeredOn: {
          name: "registeredOn",
          isArray: false,
          type: "AWSDateTime",
          isRequired: true,
          attributes: [],
        },
        updatedOn: {
          name: "updatedOn",
          isArray: false,
          type: "AWSDateTime",
          isRequired: true,
          attributes: [],
        },
        refreshTokens: {
          name: "refreshTokens",
          isArray: true,
          type: "String",
          isRequired: true,
          attributes: [],
          isArrayNullable: true,
        },
        recoveryCode: {
          name: "recoveryCode",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        status: {
          name: "status",
          isArray: false,
          type: {
            enum: "MainSupportStatuses",
          },
          isRequired: true,
          attributes: [],
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: "Companies",
      attributes: [
        {
          type: "model",
          properties: {},
        },
      ],
    },
    Demos: {
      name: "Demos",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        name: {
          name: "name",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        companyName: {
          name: "companyName",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        email: {
          name: "email",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        phoneNumber: {
          name: "phoneNumber",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        details: {
          name: "details",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        openedOn: {
          name: "openedOn",
          isArray: false,
          type: "AWSDateTime",
          isRequired: true,
          attributes: [],
        },
        updatedOn: {
          name: "updatedOn",
          isArray: false,
          type: "AWSDateTime",
          isRequired: true,
          attributes: [],
        },
        status: {
          name: "status",
          isArray: false,
          type: {
            enum: "DemosStatuses",
          },
          isRequired: true,
          attributes: [],
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: "Demos",
      attributes: [
        {
          type: "model",
          properties: {},
        },
      ],
    },
    Documentation: {
      name: "Documentation",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        public: {
          name: "public",
          isArray: false,
          type: "Boolean",
          isRequired: true,
          attributes: [],
        },
        title: {
          name: "title",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        content: {
          name: "content",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        updatedOn: {
          name: "updatedOn",
          isArray: false,
          type: "AWSDateTime",
          isRequired: true,
          attributes: [],
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: "Documentations",
      attributes: [
        {
          type: "model",
          properties: {},
        },
      ],
    },
    Support: {
      name: "Support",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        companyName: {
          name: "companyName",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        email: {
          name: "email",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        topic: {
          name: "topic",
          isArray: false,
          type: {
            enum: "MainSupportTopics",
          },
          isRequired: true,
          attributes: [],
        },
        updatedOn: {
          name: "updatedOn",
          isArray: false,
          type: "AWSDateTime",
          isRequired: true,
          attributes: [],
        },
        openedOn: {
          name: "openedOn",
          isArray: false,
          type: "AWSDateTime",
          isRequired: true,
          attributes: [],
        },
        subject: {
          name: "subject",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        details: {
          name: "details",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        status: {
          name: "status",
          isArray: false,
          type: {
            enum: "WebsiteStatuses",
          },
          isRequired: true,
          attributes: [],
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: "Supports",
      attributes: [
        {
          type: "model",
          properties: {},
        },
      ],
    },
  },
  enums: {
    PlanTypes: {
      name: "PlanTypes",
      values: ["pending", "basic", "clickify", "premium", "admin", "none", "banned"],
    },
    MainSupportStatuses: {
      name: "MainSupportStatuses",
      values: ["cancelled", "inProgress", "resolved", "unresolved", "waiting"],
    },
    DemosStatuses: {
      name: "DemosStatuses",
      values: ["waiting", "inProgress", "done", "cancelled"],
    },
    MainSupportTopics: {
      name: "MainSupportTopics",
      values: [
        "order",
        "returnsRefunds",
        "technicalIssues",
        "payments",
        "customerService",
        "security",
        "feedback",
        "other",
      ],
    },
    WebsiteStatuses: {
      name: "WebsiteStatuses",
      values: ["active", "maintenance", "inactive"],
    },
  },
  nonModels: {
    Traffic: {
      name: "Traffic",
      fields: {
        day: {
          name: "day",
          isArray: false,
          type: "AWSDateTime",
          isRequired: true,
          attributes: [],
        },
        number: {
          name: "number",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
      },
    },
    BillingAddress: {
      name: "BillingAddress",
      fields: {
        number: {
          name: "number",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        streetName: {
          name: "streetName",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        city: {
          name: "city",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        state: {
          name: "state",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        zip: {
          name: "zip",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        country: {
          name: "country",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
      },
    },
    PlanHistory: {
      name: "PlanHistory",
      fields: {
        current: {
          name: "current",
          isArray: false,
          type: "Boolean",
          isRequired: true,
          attributes: [],
        },
        plan: {
          name: "plan",
          isArray: false,
          type: {
            enum: "PlanTypes",
          },
          isRequired: true,
          attributes: [],
        },
        since: {
          name: "since",
          isArray: false,
          type: "AWSDateTime",
          isRequired: true,
          attributes: [],
        },
        exp: {
          name: "exp",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
        },
        price: {
          name: "price",
          isArray: false,
          type: "Float",
          isRequired: false,
          attributes: [],
        },
      },
    },
  },
  codegenVersion: "3.4.4",
  version: "09781d2b2e10bd1a8630bf8dd4b68f21",
};
