/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "eu-west-1",
  aws_appsync_graphqlEndpoint: "https://yd63i2nombd4ngobzfjt7qyqbe.appsync-api.eu-west-1.amazonaws.com/graphql",
  aws_appsync_region: "eu-west-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-kbjtat6cureyvfgvaarpewqgw4",
  aws_cognito_identity_pool_id: "eu-west-1:eeaec731-846a-4507-b713-2fa967e213a3",
  aws_cognito_region: "eu-west-1",
  aws_user_pools_id: "eu-west-1_Jm4nwojOU",
  aws_user_pools_web_client_id: "2aad7phql74os9cg5ee7vmp21m",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: ["REQUIRES_LOWERCASE", "REQUIRES_NUMBERS", "REQUIRES_SYMBOLS", "REQUIRES_UPPERCASE"],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_dynamodb_all_tables_region: "eu-west-1",
  aws_dynamodb_table_schemas: [
    {
      tableName: "clickify-main_companies",
      region: "eu-west-1",
    },
  ],
};

export default awsmobile;
